name: Validate Branch Name

on:
  push:
    branches:
      - 'releases/*'  # Triggers on branches that start with 'v'
    paths-ignore:
      - 'main'     # Explicitly exclude the 'main' branch
  create:
    branches:
      - 'releases/*'  # Triggers when branches that start with 'v' are created

jobs:
  validate-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract branch name
        id: branch_name
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"  # Extract branch name (releases/v1.0.1)
          BRANCH_VERSION="${BRANCH_NAME#releases/v}"  # Extract the version number (v1.0.1)
          echo "Branch name: $BRANCH_NAME"
          echo "Extracted version: $BRANCH_VERSION"
          echo "::set-output name=branch_name::$BRANCH_NAME"
          echo "::set-output name=version::$BRANCH_VERSION"

      - name: Read version from manifest.json
        id: read_version
        run: |
          MANIFEST_VERSION=$(grep -oP '(?<="version": ")[^"]*' manifest.json)
          echo "::set-output name=version::${MANIFEST_VERSION}"

      - name: Validate branch name
        run: |
          BRANCH_VERSION="${{ steps.branch_name.outputs.branch_version }}"
          MANIFEST_VERSION="${{ steps.read_version.outputs.manifest_version }}"
          
          if [ "$BRANCH_VERSION" != "$MANIFEST_VERSION" ]; then
            echo "Branch version ($BRANCH_VERSION) does not match version in manifest.json ($MANIFEST_VERSION)."
            exit 1
          else
            echo "Branch version matches the version in manifest.json."
          fi
