name: Validate Branch Name

on:
  push:
    branches:
      - 'releases/v*'  # Match branches that start with 'releases/v'
  create:
    branches:
      - 'releases/v*'  # Match branches that start with 'releases/v'

  workflow_dispatch:  # Allow manual triggers

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract branch name and version
        run: |
          echo "Extracting branch name and version..."
          BRANCH_NAME="${GITHUB_REF##*/}"  # Extract branch name (e.g., v1.0.1)
          VERSION="${BRANCH_NAME#v}"  # Extract the version number (e.g., 1.0.1)
          
          echo "Branch name: $BRANCH_NAME"
          echo "Extracted version: $VERSION"
          
          # Set environment variables
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Validate branch version matches manifest version
        run: |
          echo "Validating branch version with manifest version..."
          MANIFEST_VERSION=$(grep -oP '(?<="version": ")[^"]*' manifest.json)
          echo "Manifest version: $MANIFEST_VERSION"

          if [[ "$VERSION" != "$MANIFEST_VERSION" ]]; then
            echo "Branch version $VERSION does not match version $MANIFEST_VERSION in manifest.json."
            exit 1
          else:
            echo "Branch version $VERSION matches the version in manifest.json."
          fi
